### ISSUE TITLE
Can't instantiate the first postgres container

### ISSUE THREAD

**Issue by bdfintechpy** [mojaloop/interop-devops#11]
Hello,

I had the chance to get running this environment before, but around  last Thursday a suddenly new error shows when the provisioning is trying to get up the first docker container, almost at the very beginning. 

Specifically on the task **"start postgres"** 

File: ```/interop-devops/roles/ist/tasks/main.yml``` 

:point_down::point_down: I don't see anything strange, should be pretty much straightforward :point_down::point_down:
```
    - name: start postgres
      docker_container:
        name: postgres
        image: postgres:{{ v_postgres }}
        env:
          POSTGRES_PASSWORD: "{{ ist_pg_pass }}"
          POSTGRES_USER: "{{ ist_pg_user }}"
          SERVICE_5432_NAME: 'postgres'
        networks:
          - name: ML_IST_NET
        ports: 5432:5432
        restart_policy: always
        log_driver: syslog
        log_options:
          syslog-address: 'tcp://{{ log_ip }}:514'
          syslog-facility: daemon
          tag: postgress
      tags: db
      become: yes
```
The `Vagrantfile` is configured with `public_network` and with this schema:

VM name | IP Address
------------ | -------------
`dfsp1` | `10.20.125.43`
`dfsp2` | `10.20.125.44`
`ist` | `10.20.125.45`
`mgmt` | `10.20.125.46`

This error caught me off guard, it was passing without issues before. Any insights?

Error on stdout:

```
    mgmt: TASK [ist : Create the MOJALOOP IST docker network] ****************************
    mgmt: changed: [ist]
    mgmt: 
    mgmt: TASK [ist : start postgres] ****************************************************
    mgmt: fatal: [ist]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.20.125.45 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_L_OCup/ansible_module_docker_container.py\", line 2081, in <module>\r\n    main()\r\n  File \"/tmp/ansible_L_OCup/ansible_module_docker_container.py\", line 2076, in main\r\n    cm = ContainerManager(client)\r\n  File \"/tmp/ansible_L_OCup/ansible_module_docker_container.py\", line 1703, in __init__\r\n    self.present(state)\r\n  File \"/tmp/ansible_L_OCup/ansible_module_docker_container.py\", line 1723, in present\r\n    new_container = self.container_create(self.parameters.image, self.parameters.create_parameters)\r\n  File \"/tmp/ansible_L_OCup/ansible_module_docker_container.py\", line 825, in create_parameters\r\n    host_config=self._host_config(),\r\n  File \"/tmp/ansible_L_OCup/ansible_module_docker_container.py\", line 931, in _host_config\r\n    return self.client.create_host_config(**params)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/container.py\", line 157, in create_host_config\r\n    return utils.create_host_config(*args, **kwargs)\r\nTypeError: create_host_config() got an unexpected keyword argument 'init'\r\n", "msg": "MODULE FAILURE", "rc": 1}
    mgmt: 	to retry, use: --limit @/vagrant/create-local.retry
    mgmt: 
    mgmt: PLAY RECAP *********************************************************************
    mgmt: dfsp1                      : ok=13   changed=5    unreachable=0    failed=0   
    mgmt: dfsp2                      : ok=13   changed=5    unreachable=0    failed=0   
    mgmt: ist                        : ok=16   changed=6    unreachable=0    failed=1   
    mgmt: localhost                  : ok=14   changed=5    unreachable=0    failed=0   
    mgmt: mgmt                       : ok=15   changed=9    unreachable=0    failed=0   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
