### ISSUE TITLE
Tweaks to get provisioning working

### ISSUE THREAD

**Issue by bdfintechpy** [mojaloop/interop-devops#12]
I was striving to get up the four VMs and the provisioning successfully with the master branch.

I would like to comment/annotate/suggest here the tweaks that I had to make to get it work (Nonetheless, I'm having a fresh error on #11).

0-) You can see beforehand [here my commit](https://github.com/bdfintechpy/interop-devops/commit/46ceb120de99b603d20cd88ca83cdb138454e9c4) for the changes

1-) First of all, just after the **"Add docker repo"** task is being executed, tries to update all repos, and it doesn't throws an error perse, but when you get inside (i.e. vagrant ssh ist) and you type `apt-get update` it shows the error that the repos can't be updated. It's something about the GPG key/signature of the repo.

You can:
 
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7EA0A9C3F273FCD8` 

or go with a more clean solution and append at the beginning of File [/interop-devops/roles/provision_workers/tasks/main.yml](https://github.com/bdfintechpy/interop-devops/blob/46ceb120de99b603d20cd88ca83cdb138454e9c4/roles/provision_workers/tasks/main.yml) and then do the **"Add docker repo"**
```yml
- name: Add the GPG key for the official Docker repository to your system
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add docker repo
  become: true
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
```

2-) For some reason, the **"Docker login to JFrog"** task, always fails the first time. I have to do a `vagrant reload --provision` to make it pass through, and also I have to change the url with at `"/v2"` at the end.

Like this:
- `modusbox-level1-docker.jfrog.io/v2`
- `modusbox-level1-docker-release.jfrog.io/v2`

3-) `git` is not installed or provisioned in the `mgmt` node, so I just add that to the [provision-mgmt.sh](https://github.com/bdfintechpy/interop-devops/blob/46ceb120de99b603d20cd88ca83cdb138454e9c4/provision-mgmt.sh) to make it less problematic. 

With this sentence: `sudo apt-get -y install git`

It's necessary when Ansible installs the ELK stack.

4-) Speaking of the ELK stack, I had to make some changes to make it pass. Instead of making it listen on the interface, I had to change it to `network.host: 0.0.0.0`.
Besides that, for some reason, the syntax in the `CURL`  statement whines about the double quote, we need to put single quotes. 
Finally, we need to change the `git` protocol by putting `https` instead. 
All details [here](https://github.com/bdfintechpy/interop-devops/commit/46ceb120de99b603d20cd88ca83cdb138454e9c4#diff-574f11c5a1611243c333144e314ec545).

I'm aware that the `develop` branch might deprecate all these, nevertheless, these tweaks might be useful to someone to try and test for themselves the different end-to-end scenarios of the Mojaloop project.
