### ISSUE TITLE
problem while deploying L1P system

### ISSUE THREAD

**Issue by saminmun** [mojaloop/interop-devops#3]
Hello,

I'm trying to deploy L1P system in my test environment. I'm following the steps mentioned in https://github.com/mojaloop/interop-devops, README.md.

I have a centos 7 host. The Vagrant version is "Vagrant 2.0.2" and VirtualBox Version is "Version 5.1.6".

As stated in the README.md file after setting up the network details in the Vagrant file I run the "vagrant up" command. The deployment process runs well until I get this error and deployment exits"

```
 mgmt: TASK [request_data : command] **************************************************
    mgmt:  [WARNING]: Consider using get_url or uri module rather than running curl
    mgmt: fatal: [mgmt]: FAILED! => {"changed": true, "cmd": "curl -X POST -H \"Authorization:Basic YWRtaW46YWRtaW4=\" --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{\"name\": \"dfsp1\",\"shortName\": \"dfsp1\",\"providerUrl\": \"http://192.168.0.150:8088/scheme/adapter/v1\"}' http://192.168.0.152:8088/mock/directory/v1/commands/register", "delta": "0:00:00.013631", "end": "2018-02-25 06:48:51.984925", "msg": "non-zero return code", "rc": 7, "start": "2018-02-25 06:48:51.971294", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 192.168.0.152 port 8088: Connection refused", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 192.168.0.152 port 8088: Connection refused"], "stdout": "", "stdout_lines": []}
    mgmt: 	to retry, use: --limit @/vagrant/create-local.retry
    mgmt: 
    mgmt: PLAY RECAP *********************************************************************
    mgmt: dfsp1                      : ok=35   changed=28   unreachable=0    failed=0   
    mgmt: dfsp2                      : ok=35   changed=28   unreachable=0    failed=0   
    mgmt: ist                        : ok=9    changed=7    unreachable=0    failed=1   
    mgmt: localhost                  : ok=26   changed=18   unreachable=0    failed=0   
    mgmt: mgmt                       : ok=16   changed=13   unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
The error says connection refused to 192.168.0.152 on port 8088. According to the Vagrant file the IP belongs to the "ist" sever. When I checked the ist server I could not find any service running on port 8088. So, I'm not sure what service should be running on port 8088 for the ist server.

I have tried the whole deplyment process for multiple times. But It get stuck on this issue.

It would be of great help if someone could help to figure out the issue.

Thanks in advance

**Comment by elnyry** [comment]
@saminmun, thanks for opening this issue and the details. We will look at it and get back to you soon.

**Comment by jeffplesko** [comment]
@saminmun Do you still have the complete output from the installation attempt.  Initially, I would think that something else had a non-fatal error above this point causing the issue.  From what I can see that you have provided is that it was unable to reach the host for which it was trying to install the basic system/user accounts.  Additionally, it would help if you could please provide your Vagrantfile for validation.

If you no longer have the output, you should be able to recreate the issue by performing a `vagrant destroy` and then preforming the `vagrant up` command again.  Assuming it fails in the same place, please send me the output.

Sincerely,

Jeff Plesko

**Comment by jeffplesko** [comment]
@saminmun Please let me know if you still need assistance on this issue.

**Comment by saminmun** [comment]
Hi @jeffplesko , after few more tries this error did not occurred again. But I found another issue while installation:

```
 mgmt: TASK [elk : Add Mojaloop index to Kibana] **************************************
    mgmt: fatal: [mgmt]: FAILED! => {"changed": true, "cmd": "curl -XPOST \"http://localhost:9200/_template/l1p_template\" -H 'Content-Type: application/json' -d' { \"template\": [ \"l1p_index*\" ], \"mappings\": { \"l1p_log\": { \"_all\": { \"norms\": false }, \"dynamic_templates\": [ { \"strings_as_keyword\": { \"match_mapping_type\": \"string\", \"mapping\": { \"ignore_above\": 1024, \"type\": \"keyword\" } } } ], \"properties\": { \"@timestamp\": { \"type\": \"date\" }, \"l1p_trace_id\": { \"type\": \"keyword\" }, \"l1p_service_id\": { \"type\": \"keyword\" }, \"l1p_environment\": { \"type\": \"keyword\" }, \"l1p_call_type\": { \"type\": \"keyword\" }, \"beat\": { \"properties\": { \"hostname\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"name\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"version\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"processing_timestamp\": { \"type\": \"date\" } } }, \"input_type\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"message\": { \"type\": \"text\", \"norms\": false }, \"meta\": { \"properties\": { \"cloud\": { \"properties\": { \"availability_zone\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"instance_id\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"machine_type\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"project_id\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"provider\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"region\": { \"type\": \"keyword\", \"ignore_above\": 1024 } } } } }, \"offset\": { \"type\": \"long\" }, \"source\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"tags\": { \"type\": \"keyword\", \"ignore_above\": 1024 }, \"type\": { \"type\": \"keyword\", \"ignore_above\": 1024 } } } } }'", "delta": "0:00:01.578684", "end": "2018-02-26 07:46:52.614534", "msg": "non-zero return code", "rc": 7, "start": "2018-02-26 07:46:51.035850", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed to connect to localhost port 9200: Connection refused", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0", "  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed to connect to localhost port 9200: Connection refused"], "stdout": "", "stdout_lines": []}
    mgmt: 	to retry, use: --limit @/vagrant/create-local.retry
    mgmt: 
    mgmt: PLAY RECAP *********************************************************************
    mgmt: dfsp1                      : ok=41   changed=32   unreachable=0    failed=0   
    mgmt: dfsp2                      : ok=39   changed=30   unreachable=0    failed=0   
    mgmt: ist                        : ok=34   changed=26   unreachable=0    failed=0   
    mgmt: localhost                  : ok=26   changed=18   unreachable=0    failed=0   
    mgmt: mgmt                       : ok=84   changed=53   unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
I have attached the full installation log for this error.

[mojalooop_installlog_ELK_error.txt](https://github.com/mojaloop/interop-devops/files/1836393/mojalooop_installlog_ELK_error.txt)

Since I got stuck on this issue even after multiple installation attempts, I skipped the tags "elk","filebeat" and "curator", hoping that i could install these services later manually if necessary.

I modified the ansible command as follows:

`mgmt_config.vm.provision :shell, inline: "ansible-playbook -i /vagrant/inventory-file /vagrant/create-local.yml -e \"env=local\" --skip-tags \"elk, filebeat, curator\"", privileged: false`

After skipping these tags the installation completed.  The complete install log is attached.

[vagrant-install-log-04.txt](https://github.com/mojaloop/interop-devops/files/1836407/vagrant-install-log-04.txt)

**System Details:**

I'm trying to install Mojaloop servers in VirtualBox VMs. The Virtual box is installed on a CentOS 7 server.

The details are as follows.

0. Virtual Box Version:  `Version 5.1.6`
1.  The Operating System: 
`CentOS Linux release 7.4.1708 (Core)`
2. Cpu details:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz
Stepping:              3
CPU MHz:               3606.921
CPU max MHz:           3800.0000
CPU min MHz:           800.0000
BogoMIPS:              6816.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
```
3.  RAM

```
              total        used        free      shared  buff/cache   available
Mem:       16087332    11241200     1064216       32584     3781916     4405240
Swap:       8126460           0     812646
```
Please check the details. Please let me know if more information needed.

Now, I'm going through the documents  to figure out how could we do testing. Hope to get support for testing if any needed.

Thanks for the support!
